name: weather
recipe: laravel
config:
  php: '8.1'
  via: apache
  webroot: public
services:
  phpmyadmin:
    type: phpmyadmin
    creds:
      user: laravel
      password: laravel
      database: weather
  mysql:
    type: mysql
proxy:
  phpmyadmin:
    - "phpmyadmin.weather.lndo.site"
